version: '3.9'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    restart: on-failure
    extra_hosts:
      - host.docker.internal:host-gateway
#    depends_on:
#      - db

  db:
    container_name: db
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery:
    build: .
    command: sh -c "celery -A config.celery  worker --loglevel=INFO -B"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    env_file:
      - .env
    command: sh -c "celery -A config.celery beat "
    depends_on:
      - redis
      - db

#  nginx:
#    build:
#      context: ./nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - static_volume:/nginx/staticfiles
#    depends_on:
#      - habits
#    networks:
#      habits_network:
#        external:
#          name:
#            -habits_network


volumes:
  postgres_data:
  static_volume: